### ISSUE TITLE
Failing to update VS 2022 (Current channel) installations

### ISSUE THREAD

**Issue by gusper** [devlooped/dotnet-vs#123]
## Describe the Bug

I'm trying to update the currently installed "Current" instance of Visual Studio 2022 (Dev17). It fails though and I can see it's trying to run the Dev16 bootstrapper instead. Looks like the "Release" channel [is hardcoded to always point to the 16 ](https://github.com/devlooped/dotnet-vs/blob/68de193967e395e3d2b88091174e4809e111a961/src/VisualStudio/InstallerService.cs#L30)bootstrapper, but I haven't looked at the code enough to know if that's the issue. 

## Steps to Reproduce

* Install VS 2022 from Current channel
* Run dotnet-vs from elevated command prompt: vs update and then select the Current channel instance

## Expected Behavior

I'd expect it to run the v17 bootstrapper.

## Output

```text
vs update ?
Multiple instances found. Select the one to run:
1: Visual Studio Enterprise 2022 - Version 17.1.0 Preview 2.0 [31929.402.main]
2: Visual Studio Enterprise 2022 - Version 17.0.1
3: Visual Studio Enterprise 2022 - Version 17.1.0 Preview 1.1
You can also run [a|all] or skip one instance with !x
2
Downloading https://aka.ms/vs/16/release/vs_enterprise.exe...
The SSL connection could not be established, see inner exception.
```

## Version Info

dotnet-vs 1.1.1

**Comment by kzu** [comment]
Thanks for reporting the issue! A fix has been merged and published. Please update to the latest nuget package and let us know how it works for you.

Thanks :)

PS: sorry for taking so long :(.
